[general]
name = "regexp"
version = "2.0.0"
fix_version = "1.5.0"
description = "Provides regular expression matching."

[build]
files = [
    "regexp.fix",
    "internal/matches.fix",
    "internal/nfa.fix",
    "internal/pattern.fix",
    "internal/simple_parser.fix",
    "internal/std_bytes.fix",
    "internal/stringex.fix",
]

[build.test]
files = ["test.fix"]

[[dependencies]]
name = "hashmap"
version = "2.0.0"
git = { url = "https://github.com/tttmmmyyyy/fixlang-hashmap.git" }

[[dependencies]]
name = "character"
version = "1.0.0"
git = { url = "https://github.com/tttmmmyyyy/fixlang-character.git" }
